members:
  02:
    image_url: /images/members/02.jpg
    name: "02"
    url: https://twitter.com/cocoeyes02
  zoe:
    image_url: /images/members/zoe.jpeg
    name: "zoe"
    url: https://twitter.com/for__3
  okashoi:
    image_url: /images/members/okashoi.png
    name: "okashoi"
    url: https://twitter.com/okashoi
  shuzon:
    image_url: /images/members/shuzon.jpeg
    name: "shuzon"
    url: https://twitter.com/ShuzoN__
  ずんだまる:
    image_url: /images/members/zunda.jpeg
    name: "ずんだまる"
    url: https://twitter.com/zuncha318
author: Oysters
email: cocoeyes02@gmail.com
description: 若手ものづくり集団「Oysters」のPodcast
description_long: 若手ものづくり集団「Oysters」の所属エンジニアが、技術のことから暮らしのことまで語るPodcast
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: G-WM91B782B2
google_tag_manager: GTM-WB6N7QH
hashtag: oysters_podcast
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Oysters Podcast
url: https://oysters.dev/podcast/
