actors:
  02:
    image_url: /images/actors/02.jpg
    name: "02"
    url: https://twitter.com/cocoeyes02
author: 02
description: 若手ものづくり集団「Oysters」のPodcast
description_long: 若手ものづくり集団「Oysters」の所属エンジニアが、技術のことから暮らしのことまで語るPodcast
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: oysters_podcast
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Oysters Podcast
url: https://oystersjp.github.io/podcast/
